services:
  - type: web
    name: NOVA-XMD
    env: node
    plan: free
    repo: https://github.com/bmbtech11/NOVA-XMD
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false
